### ISSUE TITLE
Some dynamic objects' 3D bbox labels are missing

### ISSUE THREAD

**Issue by songanz** [autonomousvision/kitti360Scripts#40]
For example, in sequence "2013_05_28_drive_0000_sync", frame "0000000009", there is no 3D bbox label for the dynamic object (car) behind the vehicle. Please update the annotation. 
![image](https://user-images.githubusercontent.com/26510270/140670922-0ac1584a-a96b-4a65-b8d6-fc3eb94582f3.png)
![image](https://user-images.githubusercontent.com/26510270/140670959-952d4f9b-abf8-4a49-86b7-a3d8bb79ae52.png)

**Comment by yiyiliao** [comment]
Thank you very much for pointing out the missing label! Indeed, the dynamic label of this car is missing. For this particular case, it is due to the fact that we ignored the first 250 frames of sequence "2013_05_28_drive_0000_sync" when converting 3D labels to 2D, i.e., our 2D semantic maps start from "0000000250" for this sequence. Therefore, we also recommend ignoring the first 250 frames when using 3D LiDAR scans.

**Comment by songanz** [comment]
Thank you very much!
